In [1]:
import numpy as np

In [2]:
x = np.arange(8)

In [3]:
a = x.reshape(2,4)

b = x.reshape(-1, 2,4)

c = x.reshape(2,4,1)

d = x.reshape(-1,2,4,1)

In [7]:
a,b,c,d

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[[0, 1, 2, 3],
         [4, 5, 6, 7]]]),
 array([[[0],
         [1],
         [2],
         [3]],
 
        [[4],
         [5],
         [6],
         [7]]]),
 array([[[[0],
          [1],
          [2],
          [3]],
 
         [[4],
          [5],
          [6],
          [7]]]]))

In [38]:
e = x.reshape(2, 1, 2, 1)

ValueError: cannot reshape array of size 8 into shape (2,1,2,1)

In [37]:
e

array([[[[0, 1],
         [2, 3]]],


       [[[4, 5],
         [6, 7]]]])

In [27]:
f = x.reshape(4,1, 2)

g = x.reshape(-1, 1, 2)



In [30]:
 f,g

(array([[[0, 1]],
 
        [[2, 3]],
 
        [[4, 5]],
 
        [[6, 7]]]),
 array([[[0, 1]],
 
        [[2, 3]],
 
        [[4, 5]],
 
        [[6, 7]]]))

In [46]:
x = np.arange(32)

In [47]:
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [48]:
y = x.reshape(2,4,2,2)

In [49]:
y

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])